---
raw_text: |
  export LANG=en_US.UTF-8
  test -f /usr/bin/yum && yum install python3 -y
  test -f /usr/bin/yum && yum install epel-release -y && yum install python34 -y
  test -f /usr/bin/apt && apt install python3 -y
  
# Export here is necessary to avoid some stderr lines in some situations