---
- name: Provisioning new hosts to be Ansible-ized
  hosts: raw
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Prepare CentOS system to be managed by ansible
      include_tasks: CentOS.yml
      when: ansible_facts['distribution'] == "CentOS"

#    - name: Prepare Ubuntu system to be managed by ansible
#      include_tasks: Ubuntu.yml
#      when: 
...
