---
- name: Provisioning new hosts to be Ansible-ized
  hosts: raw
  tasks:
    - name: Install Python3
      raw: "yum install python3 -y"
    - name: Create the Ansible user
      user: 
        name: ansible
        state: present
    - name: Add SSH public keys to ansible user
      authorized_key:
        user: ansible
        key: "{{ lookup('file', '<pathtopublickey.pub>') }}"
    - name: Create sudo file
      file:
        path: /etc/sudoers.d/ansible
        state: touch
        mode: 0644
    - name: Paste sudo configuration
      copy:
        dest: /etc/sudoers.d/ansible
        content: "ansible ALL=(ALL) NOPASSWD: ALL"
...